TicketEagle/TicketEagle/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketEagle.Data;
using TicketEagle.Models;

namespace TicketEagle.Controllers
{
    public class EventosController : Controller
    {
        private readonly TEDbContext _context;

        public EventosController(TEDbContext context)
        {
            _context = context;
        }

        // GET: Eventos
        public async Task<IActionResult> Index()
        {
            var ticketEagleContext = _context.Evento.Include(e => e.Local);
            return View(await ticketEagleContext.ToListAsync());
        }

        // GET: Eventos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento
                .Include(e => e.Local)
                .FirstOrDefaultAsync(m => m.EvId == id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // GET: Eventos/Create
        [Authorize(Roles="Promotor,Admin")]
        public IActionResult Create()
        {
            ViewData["LocalFK"] = new SelectList(_context.Local, "ID", "NomeLocal");
            ViewData["PromotorEvento"] = new SelectList(_context.Set<Promotor>(), "ID", "ID");
            return View();
        }

        // POST: Eventos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EvId,Titulo,Data,Preco,LocalFK")] Evento evento,PromotorEvento prEv)
        {
            
            if (ModelState.IsValid)
            {
                _context.Add(evento);
                await _context.SaveChangesAsync();

                //relacionar evento ao promotor que o criou
                prEv.EventoFK = _context.Evento.Where(b => b.Titulo == evento.Titulo).Select(b => b.EvId).FirstOrDefault();
                prEv.PromotorFK = _context.Promotor.Where(b => b.Nome == User.Identity.Name).Select(b => b.ID).FirstOrDefault();
                _context.Add(prEv);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocalFK"] = new SelectList(_context.Local, "ID", "NomeLocal", evento.LocalFK);
            return View(evento);
        }

        // GET: Eventos/Edit/5
        [Authorize(Roles = "Promotor,Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            //verificar se o utilizador é o proprio promotor do evento para poder edita-lo
           int ip = _context.Promotor.Where(p => p.Nome == User.Identity.Name).Select(p => p.ID).FirstOrDefault();
           int ip2= _context.PromotorEvento.Where(p => p.EventoFK == id).Select(p => p.PromotorFK).FirstOrDefault();

            if (id == null)
            {
                return NotFound();
            }

            if (ip != ip2)
            {
                //nao deixa editar se nao for o proprio promotor
                return StatusCode((int)System.Net.HttpStatusCode.Unauthorized, "Acesso a este Evento Nao Autorizado");
            }
            
            var evento = await _context.Evento.FindAsync(id);
            if (evento == null)
            {
                return NotFound();
            }
            ViewData["LocalFK"] = new SelectList(_context.Local, "ID", "NomeLocal", evento.LocalFK);
            return View(evento);
        }

        // POST: Eventos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EvId,Titulo,Data,Preco,LocalFK")] Evento evento)
        {
            if (id != evento.EvId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(evento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventoExists(evento.EvId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocalFK"] = new SelectList(_context.Local, "ID", "ID", evento.LocalFK);
            return View(evento);
        }

        [Authorize(Roles = "Promotor,Admin")]
        // GET: Eventos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento
                .Include(e => e.Local)
                .FirstOrDefaultAsync(m => m.EvId == id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // POST: Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var evento = await _context.Evento.FindAsync(id);
            _context.Evento.Remove(evento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Comprar()
        {
            ViewData["EventoFK2"] = new SelectList(_context.Set<Evento>(), "EvId", "EvId");
            ViewData["IDFK"] = new SelectList(_context.Set<Utilizador>(), "UserID", "UserID");
            return View();
        }

        // POST: Bilhetes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Utilizador")]
        public async Task<IActionResult> Comprar(Bilhete bilhete, [Bind("EvId,Local,Titulo,Preco")]Evento evento)
        {

            if (ModelState.IsValid)
            {

                //var ev = _context.Evento.Where(e => e.EvId == evento.EvId).Select(b=>b.Preco).FirstOrDefault();
                var ev = await _context.Evento.FindAsync(evento.EvId);

                //encontrar nome do local
                var loc = _context.Local.Where(b => b.ID == evento.LocalFK).Select(b => b.NomeLocal).FirstOrDefault();

                //encontrar o ID Utilizador do user autenticado
                bilhete.IDFK = _context.Utilizador.Where(b => b.Nome == User.Identity.Name).Select(b => b.UserID).FirstOrDefault();
                bilhete.email = User.Identity.Name;
                bilhete.DataCompra = DateTime.Now;

                //recebe preco do evento atraves do nome do select
                if (ev.Preco == 0)
                {
                    var p = Request.Form["pr"];
                    bilhete.Preco = decimal.Parse(Request.Form["pr"]);
                }
                else
                {
                    bilhete.Preco = ev.Preco;
                }

                bilhete.Descrição = string.Concat(loc, ev.Titulo);
                bilhete.EventoFK2 = evento.EvId;
                _context.Add(bilhete);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventoFK2"] = new SelectList(_context.Set<Evento>(), "EvId", "EvId", bilhete.EventoFK2);
            ViewData["IDFK"] = new SelectList(_context.Set<Utilizador>(), "UserID", "UserID", bilhete.IDFK);
            // ViewData["conf"] = "<script>alert('Change succesfully');</script>";
            //return View(bilhete);
            return RedirectToAction(nameof(Index));
        }

        private bool EventoExists(int id)
        {
            return _context.Evento.Any(e => e.EvId == id);
        }
    }
}

TicketEagle/TicketEagle/Controllers/LocaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketEagle.Data;
using TicketEagle.Models;

namespace TicketEagle.Controllers
{
    public class LocaisController : Controller
    {
        private readonly TEDbContext _context;

        public LocaisController(TEDbContext context)
        {
            _context = context;
        }

        // GET: Locais
        public async Task<IActionResult> Index()
        {
            return View(await _context.Local.ToListAsync());
        }

        // GET: Locais/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var local = await _context.Local
                .FirstOrDefaultAsync(m => m.ID == id);
            if (local == null)
            {
                return NotFound();
            }

            return View(local);
        }

        [Authorize(Roles = "Promotor,Admin")]
        // GET: Locais/Create
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Promotor,Admin")]
        // POST: Locais/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,NomeLocal,Descrição,Capacidade,Foto")] Local local)
        {
            if (ModelState.IsValid)
            {
                _context.Add(local);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(local);
        }

        [Authorize(Roles = "Promotor,Admin")]
        // GET: Locais/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var local = await _context.Local.FindAsync(id);
            if (local == null)
            {
                return NotFound();
            }
            return View(local);
        }

        // POST: Locais/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Promotor,Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ID,NomeLocal,Descrição,Capacidade,Foto")] Local local)
        {
            if (id != local.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(local);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocalExists(local.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(local);
        }

        [Authorize(Roles = "Promotor,Admin")]
        // GET: Locais/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var local = await _context.Local
                .FirstOrDefaultAsync(m => m.ID == id);
            if (local == null)
            {
                return NotFound();
            }

            return View(local);
        }

        // POST: Locais/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var local = await _context.Local.FindAsync(id);
            _context.Local.Remove(local);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocalExists(int id)
        {
            return _context.Local.Any(e => e.ID == id);
        }
    }
}

TicketEagle/TicketEagle/Controllers/PromotoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketEagle.Data;
using TicketEagle.Models;

namespace TicketEagle.Controllers
{
    public class PromotoresController : Controller
    {
        private readonly TEDbContext _context;

        public PromotoresController(TEDbContext context)
        {
            _context = context;
        }

        // GET: Promotores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Promotor.ToListAsync());
        }

        // GET: Promotores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotor = await _context.Promotor
                .FirstOrDefaultAsync(m => m.ID == id);
            if (promotor == null)
            {
                return NotFound();
            }

            return View(promotor);
        }

        // GET: Promotores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Promotores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nome,Email,Password,Foto")] Promotor promotor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(promotor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(promotor);
        }

        // GET: Promotores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotor = await _context.Promotor.FindAsync(id);
            if (promotor == null)
            {
                return NotFound();
            }
            return View(promotor);
        }

        // POST: Promotores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nome,Email,Password,Foto")] Promotor promotor)
        {
            if (id != promotor.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(promotor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PromotorExists(promotor.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(promotor);
        }

        // GET: Promotores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotor = await _context.Promotor
                .FirstOrDefaultAsync(m => m.ID == id);
            if (promotor == null)
            {
                return NotFound();
            }

            return View(promotor);
        }

        // POST: Promotores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var promotor = await _context.Promotor.FindAsync(id);
            _context.Promotor.Remove(promotor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PromotorExists(int id)
        {
            return _context.Promotor.Any(e => e.ID == id);
        }
    }
}

TicketEagle/TicketEagle/Views/Shared/_Layout.cshtml
@*
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - TicketEagle</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <img src="~/assets/img/TicketEagle.PNG" height="50" alt="Logo"/>
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TicketEagle</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bilhetes" asp-action="Index">Bilhetes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Eventos" asp-action="Index">Eventos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Utilizadores" asp-action="Index">Utilizadores</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav flex-grow-1 flex-row-reverse">
                            <li class="nav-item">
                                <partial name="_LoginPartial.cshtml" />
                            </li>
                        </ul>
                    </div>

                </div>
            </nav>
        </header>
        
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - TicketEagle - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
    </html>
*@

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] - TicketEagle</title>
    <meta content="" name="descriptison">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Day - v2.1.0
    * Template URL: https://bootstrapmade.com/day-multipurpose-html-template-for-free/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>


    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top ">
        <div class="container d-flex align-items-center">


            <!-- Uncomment below if you prefer to use an image logo <h1 class="logo mr-auto"><a href="index.html">Day</a></h1>-->
            <a  asp-area="" asp-controller="Home" asp-action="Index"><img src="~/assets/img/TicketEagle.PNG" height="100" width="100" alt="" class="img-fluid"></a>

            <nav class="nav-menu d-none d-lg-block" display="inline">
                <ul>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Eventos" asp-action="Index">Eventos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Utilizadores" asp-action="Index">Utilizadores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Promotores" asp-action="Index">Promotores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Locais" asp-action="Index">Locais</a>
                    </li>
                    <li class="nav-item">
                        <partial name="_LoginPartial.cshtml" />
                    </li>
                </ul>
            </nav><!-- .nav-menu -->

        </div>
    </header><!-- End Header -->
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-4 col-md-6">
                        <div class="footer-info">
                            <h3>TicketEagle</h3>
                            <div class="social-links mt-3">
                                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6 col-md-6 footer-links text-center">
                        <h2>Instituto Politecnico de Tomar</h2>
                        <h3>Engenharia Informatica</h3>
                        <h4>Tecnologias da Internet II</h4>
                        <br />
                        <img src="assets/img/dev.png" alt="" width="110" height="110">
                        <p>Ruben Salgado nº21374</p>
                    </div>





                </div>
            </div>
        </div>

                <div class="container">
                    <div class="copyright">
                        &copy; Copyright <strong><span>Day</span></strong>. All Rights Reserved
                    </div>
                    <div class="credits">
                        <!-- All the links in the footer should remain intact. -->
                        <!-- You can delete the links only if you purchased the pro version. -->
                        <!-- Licensing information: https://bootstrapmade.com/license/ -->
                        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/day-multipurpose-html-template-for-free/ -->
                        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                    </div>
                </div>
</footer><!-- End Footer -->

    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="assets/vendor/jquery/jquery.min.js"></script>
    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="assets/vendor/php-email-form/validate.js"></script>
    <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="assets/vendor/venobox/venobox.min.js"></script>
    <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="assets/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="assets/js/main.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>