TicketEagle/TicketEagle/Models/Evento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TicketEagle.Models
{
    public class Evento
    {
        public Evento()
        {
            Bilhete = new HashSet<Bilhete>();
            PromotorEvento = new HashSet<PromotorEvento>();
        }

        [Key]
        public int EvId { get; set; }

        [MaxLength(50)]
        public string Titulo { get; set; }

        public DateTime Data { get; set; }

        [Column(TypeName = "decimal(10,2)")]
        public decimal Preco { get; set; }

        //FK para o local
        [ForeignKey(nameof(Local))]
        public int LocalFK { get; set; }
        public virtual Local Local { get; set; }

        public virtual ICollection<Bilhete> Bilhete { get; set; }

        public virtual ICollection<PromotorEvento> PromotorEvento { get; set; }
    }
}

TicketEagle/TicketEagle/Controllers/BilhetesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketEagle.Data;
using TicketEagle.Models;
using Microsoft.AspNetCore.Identity;
using TicketEagle.Areas.Identity.Data;

namespace TicketEagle.Controllers
{
    public class BilhetesController : Controller
    {
        private readonly TEDbContext _context;
        private readonly UserManager<TicketEagleUser> _userManager;

        public BilhetesController(TEDbContext context,UserManager<TicketEagleUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Bilhetes
        public async Task<IActionResult> Index()
        {
            var ticketEagleContext = _context.Bilhete.Include(b => b.EvId).Include(b => b.UserID);
            return View(await ticketEagleContext.ToListAsync());
        }

        // GET: Bilhetes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bilhete = await _context.Bilhete
                .Include(b => b.EvId)
                .Include(b => b.UserID)
                .FirstOrDefaultAsync(m => m.TicketID == id);
            if (bilhete == null)
            {
                return NotFound();
            }

            return View(bilhete);
        }

        // GET: Bilhetes/Create
        public IActionResult Create()
        {
            ViewData["EventoFK2"] = new SelectList(_context.Set<Evento>(), "EvId", "EvId");
            ViewData["IDFK"] = new SelectList(_context.Set<Utilizador>(), "UserID", "UserID");
            return View();
        }

        // POST: Bilhetes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TicketID,email,Descrição,DataCompra,EventoFK2,Preco,IDFK")] Bilhete bilhete)
        {
            if (ModelState.IsValid)
            {
                //encontrar o ID Utilizador do user autenticado, adicionar data de compra e criar o bilhete
                bilhete.IDFK = _context.Utilizador.Where(b => b.Nome == User.Identity.Name).Select(b =>b.UserID).FirstOrDefault();
                bilhete.email = User.Identity.Name;
                bilhete.DataCompra = DateTime.Now;
                _context.Add(bilhete);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventoFK2"] = new SelectList(_context.Set<Evento>(), "EvId", "EvId", bilhete.EventoFK2);
            ViewData["IDFK"] = new SelectList(_context.Set<Utilizador>(), "UserID", "UserID", bilhete.IDFK);
            return View(bilhete);
        }

        // GET: Bilhetes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bilhete = await _context.Bilhete.FindAsync(id);
            if (bilhete == null)
            {
                return NotFound();
            }
            ViewData["EventoFK2"] = new SelectList(_context.Set<Evento>(), "EvId", "EvId", bilhete.EventoFK2);
            ViewData["IDFK"] = new SelectList(_context.Set<Utilizador>(), "UserID", "UserID", bilhete.IDFK);
            return View(bilhete);
        }

        // POST: Bilhetes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TicketID,email,Descrição,DataCompra,EventoFK2,Preco,IDFK")] Bilhete bilhete)
        {
            if (id != bilhete.TicketID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bilhete);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BilheteExists(bilhete.TicketID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventoFK2"] = new SelectList(_context.Set<Evento>(), "EvId", "EvId", bilhete.EventoFK2);
            ViewData["IDFK"] = new SelectList(_context.Set<Utilizador>(), "UserID", "UserID", bilhete.IDFK);
            return View(bilhete);
        }

        // GET: Bilhetes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bilhete = await _context.Bilhete
                .Include(b => b.EvId)
                .Include(b => b.UserID)
                .FirstOrDefaultAsync(m => m.TicketID == id);


            if (bilhete == null)
            {
                return NotFound();
            }

            return View(bilhete);
        }

        // POST: Bilhetes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bilhete = await _context.Bilhete.FindAsync(id);
            _context.Bilhete.Remove(bilhete);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BilheteExists(int id)
        {
            return _context.Bilhete.Any(e => e.TicketID == id);
        }
    }
}

TicketEagle/TicketEagle/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketEagle.Data;
using TicketEagle.Models;

namespace TicketEagle.Controllers
{
    public class EventosController : Controller
    {
        private readonly TEDbContext _context;

        public EventosController(TEDbContext context)
        {
            _context = context;
        }

        // GET: Eventos
        public async Task<IActionResult> Index()
        {
            var ticketEagleContext = _context.Evento.Include(e => e.Local);
            return View(await ticketEagleContext.ToListAsync());
        }

        // GET: Eventos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento
                .Include(e => e.Local)
                .FirstOrDefaultAsync(m => m.EvId == id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // GET: Eventos/Create
        [Authorize(Roles="Promotor,Admin")]
        public IActionResult Create()
        {
            ViewData["LocalFK"] = new SelectList(_context.Local, "ID", "NomeLocal");
            ViewData["PromotorEvento"] = new SelectList(_context.Set<Promotor>(), "ID", "ID");
            return View();
        }

        // POST: Eventos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EvId,Titulo,Data,Preco,LocalFK")] Evento evento,PromotorEvento prEv)
        {
            
            if (ModelState.IsValid)
            {
                _context.Add(evento);
                await _context.SaveChangesAsync();

                //relacionar evento ao promotor que o criou
                prEv.EventoFK = _context.Evento.Where(b => b.Titulo == evento.Titulo).Select(b => b.EvId).FirstOrDefault();
                prEv.PromotorFK = _context.Promotor.Where(b => b.Nome == User.Identity.Name).Select(b => b.ID).FirstOrDefault();
                _context.Add(prEv);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocalFK"] = new SelectList(_context.Local, "ID", "NomeLocal", evento.LocalFK);
            return View(evento);
        }

        // GET: Eventos/Edit/5
        [Authorize(Roles = "Promotor,Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            //verificar se o utilizador é o proprio promotor do evento para poder edita-lo
           int ip = _context.Promotor.Where(p => p.Nome == User.Identity.Name).Select(p => p.ID).FirstOrDefault();
           int ip2= _context.PromotorEvento.Where(p => p.EventoFK == id).Select(p => p.PromotorFK).FirstOrDefault();

            if (id == null)
            {
                return NotFound();
            }

            if (ip != ip2)
            {
                //nao deixa editar se nao for o proprio promotor
                return StatusCode((int)System.Net.HttpStatusCode.Unauthorized, "Acesso a este Evento Nao Autorizado");
            }
            
            var evento = await _context.Evento.FindAsync(id);
            if (evento == null)
            {
                return NotFound();
            }
            ViewData["LocalFK"] = new SelectList(_context.Local, "ID", "NomeLocal", evento.LocalFK);
            return View(evento);
        }

        // POST: Eventos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EvId,Titulo,Data,Preco,LocalFK")] Evento evento)
        {
            if (id != evento.EvId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(evento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventoExists(evento.EvId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocalFK"] = new SelectList(_context.Local, "ID", "ID", evento.LocalFK);
            return View(evento);
        }

        [Authorize(Roles = "Promotor,Admin")]
        // GET: Eventos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento
                .Include(e => e.Local)
                .FirstOrDefaultAsync(m => m.EvId == id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // POST: Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var evento = await _context.Evento.FindAsync(id);
            _context.Evento.Remove(evento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Comprar()
        {
            ViewData["EventoFK2"] = new SelectList(_context.Set<Evento>(), "EvId", "EvId");
            ViewData["IDFK"] = new SelectList(_context.Set<Utilizador>(), "UserID", "UserID");
            return View();
        }

        // POST: Bilhetes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Utilizador")]
        public async Task<IActionResult> Comprar(Bilhete bilhete, [Bind("EvId,Local,Titulo,Preco")]Evento evento)
        {

            if (ModelState.IsValid)
            {

                //var ev = _context.Evento.Where(e => e.EvId == evento.EvId).Select(b=>b.Preco).FirstOrDefault();
                var ev = await _context.Evento.FindAsync(evento.EvId);

                //encontrar nome do local
                var loc = _context.Local.Where(b => b.ID == evento.LocalFK).Select(b => b.NomeLocal).FirstOrDefault();

                //encontrar o ID Utilizador do user autenticado
                bilhete.IDFK = _context.Utilizador.Where(b => b.Nome == User.Identity.Name).Select(b => b.UserID).FirstOrDefault();
                bilhete.email = User.Identity.Name;
                bilhete.DataCompra = DateTime.Now;

                //recebe preco do evento atraves do nome do select
                if (ev.Preco == 0)
                {
                    var p = Request.Form["pr"];
                    bilhete.Preco = decimal.Parse(Request.Form["pr"]);
                }
                else
                {
                    bilhete.Preco = ev.Preco;
                }

                bilhete.Descrição = string.Concat(loc, ev.Titulo);
                bilhete.EventoFK2 = evento.EvId;
                _context.Add(bilhete);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventoFK2"] = new SelectList(_context.Set<Evento>(), "EvId", "EvId", bilhete.EventoFK2);
            ViewData["IDFK"] = new SelectList(_context.Set<Utilizador>(), "UserID", "UserID", bilhete.IDFK);
            // ViewData["conf"] = "<script>alert('Change succesfully');</script>";
            //return View(bilhete);
            return RedirectToAction(nameof(Index));
        }

        private bool EventoExists(int id)
        {
            return _context.Evento.Any(e => e.EvId == id);
        }
    }
}

TicketEagle/TicketEagle/Views/Eventos/Create.cshtml
@model TicketEagle.Models.Evento

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h1>Criar Evento</h1>

<h4>Evento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input type="datetime-local" asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocalFK" class="control-label"></label>
                <select asp-for="LocalFK" class="form-control" asp-items="ViewBag.LocalFK"></select>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TicketEagle/TicketEagle/Views/Eventos/Delete.cshtml
@model TicketEagle.Models.Evento

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Evento</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Local)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Local.ID)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="EvId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TicketEagle/TicketEagle/Views/Eventos/Details.cshtml
@model TicketEagle.Models.Evento

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h1>Detalhes</h1>

<div>
    <h4>Evento</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Local)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Local.ID)
        </dd>
    </dl>
</div>

@if (@Model.Bilhete.Count() == 0)
{
    <h4>Lista de consultas associadas ao/à @Model.Local em @Model.Data </h4>
}
else
{
    <table class="table">
        <tr>
            <th>Descrição</th>
            <th>Preço</th>
        </tr>
        @foreach (var bilhete in Model.Bilhete)
        { // listar todos os bilhetes deste utilizador
            <tr>
                <td>@bilhete.Descrição</td>
                <td>@bilhete.Preco</td>
                <td>
                    @*criar bilhete quando carrega no butao *@
                    <a asp-controller="Bilhetes" asp-action="Details" asp-route-id="@bilhete.TicketID">Comprar</a>
                </td>
            </tr>
        }
    </table>
}
<div>
    <a asp-action="Edit" asp-route-id="@Model.EvId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TicketEagle/TicketEagle/Views/Eventos/Edit.cshtml
@model TicketEagle.Models.Evento

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h1>Edit</h1>

<h4>Evento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EvId" />
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocalFK" class="control-label"></label>
                <select asp-for="LocalFK" class="form-control" asp-items="ViewBag.LocalFK"></select>
                <span asp-validation-for="LocalFK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TicketEagle/TicketEagle/Views/Eventos/Index.cshtml
@model IEnumerable<TicketEagle.Models.Evento>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
   <br /><br /><br /><br /><br /><br /><br />

<h1>Lista de Eventos</h1>

<p>
    <a asp-action="Create" class="btn btn-info">Criar Evento</a>
</p>
@if (Model.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Data)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Local)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Titulo)
                </th>
                @*<th>
            @Html.DisplayNameFor(model => model.PromotorEvento)
        </th>*@
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                @if (item.Data.CompareTo(DateTime.Now)>0) { 
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Data)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Local.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                @*
        <td>
            @Html.DisplayFor(modelItem => item.PromotorEvento)
        </td>*@
                <td>
                    @*<a asp-action="Comprar" class="btn btn-info">Comprar</a>*@

                    <form asp-action="Comprar" asp-route-EvId="@item.EvId">
                        @if (item.Preco == 0)
                        {
                            <select name="pr" asp-for="@item.Preco">
                                <option value="20">20€</option>
                                <option value="40">40€</option>
                                <option value="80">80€</option>
                            </select>
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.Preco)
                        }
                        <div><input type="submit" value="Comprar" class="btn btn-outline-danger" onclick="if(confirm('Tem a certeza que quer comprar?')) { alert('Compra Efetuada') }" /></div>
                    </form>


                    <a asp-action="Edit" asp-route-id="@item.EvId" class="btn btn-success">Editar</a>
                    <a asp-action="Details" asp-route-id="@item.EvId" class="btn btn-secondary">Detalhes</a>
                    <a asp-action="Delete" asp-route-id="@item.EvId" class="btn btn-danger">Apagar</a>
                </td>
            </tr>
                }
            }
        </tbody>
    </table>

}
else
{
    <kbd>Não há Eventos disponiveis</kbd>
}